# Generated by Django 4.1.1 on 2024-12-06 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='description',
            new_name='nameoffer',
        ),
    ]
