# Generated by Django 4.1.1 on 2024-12-20 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_fueltype'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='fuel_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.fueltype'),
        ),
    ]
