# Generated by Django 4.1.1 on 2024-12-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_offer_fuel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='km',
            field=models.IntegerField(default=0),
        ),
    ]
