name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Check deployment settings
      run: python manage.py check --deploy

    - name: Collect static files
      run: python manage.py collectstatic --no-input

    - name: Deploy to Render
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        api-key: ${{ secrets.RENDER_API_KEY }}
        service-id: srv-ctcs7fi3esus73blr3e0?key=3tr7t4SR7PM
        wait-for-success: true
